# Header

menu:
  主页: /

# SubNav
subnav:
  github: "https://github.com/BitterPotato"
  jianshu: "http://www.jianshu.com/u/44c59ee619e2"
  bilibili: "http://space.bilibili.com/2110219/#!/"
  mail: "yangwj.zju@foxmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more

show_all_link: '展开全文'
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true
# Miscellaneous
google_analytics: ''
favicon: /imgs/settings/favicon.ico

#你的头像url
avatar: /imgs/settings/avatar.jpg

#是否开启分享
share_jia: true
share_addthis: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  #friends: 'false'
  aboutme: '关于我'

#friends:
  #友情链接1: http://localhost:4000/
  #友情链接2: http://localhost:4000/
  #友情链接3: http://localhost:4000/
  #友情链接4: http://localhost:4000/
  #友情链接5: http://localhost:4000/
  #友情链接6: http://localhost:4000/

aboutme: 这个人懒死了，什么都没有写('・ˍ・ `)